version: 2

sources:
  - name: erp_humanresources
    database: adventure_works
    schema: pg_humanresources
    tables:
      - name: department
        columns:
          - name: departmentid
            tests:
              - unique
              - not_null
      - name: employee
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
  - name: erp_person
    database: adventure_works
    schema: pg_person
    tables:
      - name: address
        columns:
          - name: addressid
            tests:
              - unique
              - not_null
      - name: businessentity
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: businessentityaddress
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - businessentityid
                - addressid
                - addresstypeid
      - name: businessentitycontact
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - businessentityid
                - contacttypeid
                - personid
          - not_null:
              column_name: businessentityid
          - not_null:
              column_name: contacttypeid
          - not_null:
              column_name: personid
      - name: contacttype
        columns:
          - name: contacttypeid
            tests:
              - unique
              - not_null
      - name: countryregion
        columns:
          - name: countryregioncode
            tests:
              - unique
              - not_null
      - name: emailaddress
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
          - name: emailaddressid
            tests:
              - unique
              - not_null
      - name: person
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: stateprovince
        columns:
          - name: stateprovinceid
            tests:
              - unique
              - not_null
  - name: erp_production
    database: adventure_works
    schema: pg_production
    tables:
      - name: billofmaterials
        columns:
          - name: billofmaterialsid
            tests:
              - unique
              - not_null
      - name: product
        columns:
          - name: productid
            tests:
              - unique
              - not_null
      - name: productcategory
        columns:
          - name: productcategoryid
            tests:
              - unique
              - not_null
      - name: productinventory
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - locationid
                - productid
          - not_null:
              column_name: locationid
          - not_null:
              column_name: productid
      - name: productlistpricehistory
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - productid
                - startdate
          - not_null:
              column_name: productid
          - not_null:
              column_name: startdate
      - name: productmodel
        columns:
          - name: productmodelid
            tests:
              - unique
              - not_null
      - name: productreview
        columns:
          - name: productreviewid
            tests:
              - unique
              - not_null
      - name: productsubcategory
        columns:
          - name: productsubcategoryid
            tests:
              - unique
              - not_null
      - name: productcosthistory
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - productid
                - startdate
          - not_null:
              column_name: productid
          - not_null:
              column_name: startdate
  - name: erp_purchasing
    database: adventure_works
    schema: pg_purchasing
    tables:
      - name: productvendor
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - businessentityid
                - productid
          - not_null:
              column_name: businessentityid
          - not_null:
              column_name: productid
      - name: purchaseorderdetail
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - purchaseorderdetailid
                - purchaseorderid
          - not_null:
              column_name: purchaseorderdetailid
          - not_null:
              column_name: purchaseorderid
      - name: shipmethod
        columns:
          - name: shipmethodid
            tests:
              - unique
              - not_null
      - name: vendor
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
  - name: erp_sales
    database: adventure_works
    schema: pg_sales
    tables:
      - name: countryregioncurrency
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - countryregioncode
                - currencycode
          - not_null:
              column_name: countryregioncode
          - not_null:
              column_name: currencycode
      - name: creditcard
        columns:
          - name: creditcardid
            tests:
              - unique
              - not_null
      - name: currency
        columns:
          - name: currencycode
            tests:
              - unique
              - not_null
      - name: currencyrate
        columns:
          - name: currencyrateid
            tests:
              - unique
              - not_null
      - name: customer
        columns:
          - name: customerid
            tests:
              - unique
              - not_null
      - name: personcreditcard
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
          - name: creditcardid
            tests:
              - unique
              - not_null
      - name: salesorderdetail
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - salesorderdetailid
                - salesorderid
          - not_null:
              column_name: salesorderdetailid
          - not_null:    
              column_name: salesorderid
      - name: salesorderheader
        columns:
          - name: salesorderid
            tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - salesorderid
                - salesreasonid
          - not_null:
              column_name: salesorderid
          - not_null:
              column_name: salesreasonid
      - name: salesperson
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: salespersonquotahistory
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - businessentityid
                - quotadate
          - not_null:
              column_name: businessentityid
          - not_null:
              column_name: quotadate
      - name: salesreason
        columns:
          - name: salesreasonid
            tests:
              - unique
              - not_null
      - name: salestaxrate
        columns:
          - name: salestaxrateid
            tests:
              - unique
              - not_null
      - name: salesterritory
        columns:
          - name: territoryid
            tests:
              - unique
              - not_null
      - name: salesterritoryhistory
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - businessentityid
                - startdate
                - territoryid
          - not_null:
              column_name: businessentityid
          - not_null:
              column_name: startdate
          - not_null:
              column_name: territoryid
      - name: shoppingcartitem
        columns:
          - name: shoppingcartitemid
            tests:
              - unique
              - not_null
      - name: specialoffer
        columns:
          - name: specialofferid
            tests:
              - unique
              - not_null
      - name: specialofferproduct
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - productid
                - specialofferid
          - not_null:
              column_name: productid
          - not_null:
              column_name: specialofferid
      - name: store
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
